version: '3.9'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: "server /export --address :9000 --console-address :9001"
    volumes:
      - ./docker/minio/data:/export